# Generated by Django 3.0.2 on 2020-09-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='labour_markup',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='globalpreferences',
            name='labour_rate',
            field=models.FloatField(default=1.0),
        ),
    ]
