# Generated by Django 3.0.2 on 2020-09-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('preferences', '0002_auto_20181220_0803'),
        ('landing_page', '0002_auto_20200903_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalPreferences',
            new_name='GlobalPreference',
        ),
    ]
