# Generated by Django 3.0.2 on 2020-09-06 01:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=80)),
                ('part_number', models.CharField(max_length=30, verbose_name='Part Number')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0, verbose_name='Stock')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('part_number', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('supplier_invoice', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Invoice Number cannot contain non-numeric characters')], verbose_name='Invoice Number')),
                ('po', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='PO Number cannot contain non-numeric characters')], verbose_name='PO Number')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_return', models.BooleanField(default=False, verbose_name='Return?')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Invoice Number cannot contain non-numeric characters')], verbose_name='Reference Invoice Number')),
                ('comments', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('returnedqty', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total returned')),
                ('retqty', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Return Qty')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('core', models.BooleanField(default=False, verbose_name='Core?')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Promotion?')),
                ('package_size', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, max_length=50)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sup_invoices.Part')),
                ('prices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sup_invoices.Prices')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts_db.Business')),
                ('supplier_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sup_invoices.SupplierInvoice')),
            ],
            options={
                'verbose_name_plural': 'Part Purchase History',
            },
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='purchased_parts',
            field=models.ManyToManyField(related_name='purchased_parts', through='sup_invoices.SupplierInvoiceParts', to='sup_invoices.Part'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts_db.Business'),
        ),
        migrations.AddField(
            model_name='prices',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='prices', through='sup_invoices.SupplierInvoiceParts', to='sup_invoices.Part'),
        ),
    ]
