# Generated by Django 3.0.2 on 2020-09-04 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enginecode', models.CharField(max_length=100, verbose_name='Engine Code')),
            ],
        ),
        migrations.CreateModel(
            name='EngineSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enginesize', models.CharField(max_length=100, verbose_name='Engine Size')),
            ],
        ),
        migrations.CreateModel(
            name='MakeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('vehiclemodel', models.CharField(max_length=100, verbose_name='Model')),
                ('makemodel', models.CharField(max_length=100, verbose_name='Make and Model')),
                ('comments', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim', models.CharField(max_length=100, verbose_name='Trim')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle', models.TextField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020)),
                ('transmission_type', models.CharField(choices=[('u', '--'), ('a', 'Auto'), ('m', 'Manual')], default='a', max_length=1)),
                ('drive_wheel', models.CharField(choices=[('u', '--'), ('f', 'Front'), ('r', 'Rear'), ('a', 'AWD'), ('4', '4x4'), ('t', 'Trailer')], default='f', max_length=1)),
                ('rear_brake_style', models.CharField(choices=[('uk', '--'), ('di', 'Disk'), ('dr', 'Drum')], default='di', max_length=2)),
                ('e_brake_style', models.CharField(choices=[('u', '--'), ('m', 'Mechanical'), ('e', 'Electrical')], default='m', max_length=1)),
                ('brake_note', models.TextField(blank=True, max_length=200, verbose_name='Brake notes')),
                ('power_steering_type', models.CharField(choices=[('u', '--'), ('h', 'Hydraulic'), ('e', 'Electrical')], default='h', max_length=1)),
                ('absys', models.CharField(choices=[('u', '--'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='ABS')),
                ('tpms', models.CharField(choices=[('u', '--'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='TPMS')),
                ('ac', models.CharField(choices=[('u', '--'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='AC')),
                ('tire_size_prefix', models.CharField(blank=True, choices=[('u', 'Custom'), ('', ''), ('LT', 'LT'), ('P', 'P')], default='', max_length=2)),
                ('tire_size', models.CharField(blank=True, max_length=15)),
                ('comments', models.TextField(blank=True, max_length=200)),
                ('vehicle_enginecode', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles_db.EngineCode', verbose_name='Engine Code')),
                ('vehicle_enginesize', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles_db.EngineSize', verbose_name='Engine Size')),
                ('vehicle_makemodel', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vehicles_db.MakeModel', verbose_name='Make and Model')),
                ('vehicle_trim', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles_db.Trim', verbose_name='Trim')),
            ],
        ),
    ]
