# Generated by Django 3.0.2 on 2020-09-06 01:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import workorders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientcars_db', '0001_initial'),
        ('sup_invoices', '0001_initial'),
        ('contacts_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.IntegerField(default=workorders.models.Estimation.number, unique=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientcars_db.Client')),
            ],
        ),
        migrations.CreateModel(
            name='EstimationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('technician_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('test_results', models.TextField(blank=True, max_length=200, null=True)),
                ('internal_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('hours_charged', models.FloatField(default=0.0)),
                ('labour_guide', models.FloatField(default=0.0, verbose_name='Labour Guide Hours')),
                ('labour_charged', models.FloatField(default=0.0, verbose_name='Labour Charged ($)')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.Estimation', verbose_name='Estimation')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField(default=workorders.models.Invoice.number, unique=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientcars_db.Client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('technician_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('test_results', models.TextField(blank=True, max_length=200, null=True)),
                ('internal_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('hours_charged', models.FloatField(default=0.0)),
                ('labour_guide', models.FloatField(default=0.0, verbose_name='Labour Guide Hours')),
                ('labour_charged', models.FloatField(default=0.0, verbose_name='Labour Charged ($)')),
                ('status', models.CharField(choices=[('b', 'Billed'), ('p', 'Paid')], default='b', max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.Invoice', verbose_name='Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='LineParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('estimationline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.EstimationLine')),
                ('invoiceline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.InvoiceLine')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sup_invoices.Part')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(default=workorders.models.WorkOrder.number, max_length=200, unique=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientcars_db.Client')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('technician_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('test_results', models.TextField(blank=True, max_length=200, null=True)),
                ('internal_comments', models.TextField(blank=True, max_length=200, null=True)),
                ('hours_charged', models.FloatField(default=0.0)),
                ('labour_guide', models.FloatField(default=0.0, verbose_name='Labour Guide Hours')),
                ('labour_charged', models.FloatField(default=0.0, verbose_name='Labour Charged ($)')),
                ('status', models.CharField(choices=[('c', 'Cancelled'), ('o', 'Ongoing'), ('d', 'Completed')], default='o', max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.WorkOrder', verbose_name='Work Order')),
                ('parts', models.ManyToManyField(blank=True, related_name='workorderline', related_query_name='workorderline', through='workorders.LineParts', to='sup_invoices.Part')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts_db.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='lineparts',
            name='workorderline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.WorkOrderLine'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='invoiceline', related_query_name='invoiceline', through='workorders.LineParts', to='sup_invoices.Part'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts_db.Contact'),
        ),
        migrations.AddField(
            model_name='estimationline',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='estimationline', related_query_name='estimationline', through='workorders.LineParts', to='sup_invoices.Part'),
        ),
        migrations.AddField(
            model_name='estimationline',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts_db.Contact'),
        ),
    ]
